In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir('C:/pytest')

In [3]:
df = pd.read_csv('감성대화말뭉치(최종데이터)_Training.csv', encoding='cp949')

c:\project\venv\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
df.head()

번호   연령  성별       상황키워드    신체질환 감정_대분류   감정_소분류  \
0  44164.0   청년  남성  연애, 결혼, 출산    해당없음     기쁨     신이 난   
1   3926.0   노년  남성      건강, 죽음  만성질환 유     불안  스트레스 받는   
2  50882.0  청소년  여성     학업 및 진로    해당없음     당황       당황   
3  31303.0   노년  남성          재정  만성질환 무     기쁨     신이 난   
4  47200.0   노년  여성          재정  만성질환 유     기쁨       안도   

                                           사람문장1  \
0                      아내가 드디어 출산하게 되어서 정말 신이 나.   
1        당뇨랑 합병증 때문에 먹어야 할 약이 열 가지가 넘어가니까 스트레스야.   
2        고등학교에 올라오니 중학교 때보다 수업이 갑자기 어려워져서 당황스러워.   
3  재취업이 돼서 받게 된 첫 월급으로 온 가족이 외식을 할 예정이야. 너무 행복해.   
4                   빚을 드디어 다 갚게 되어서 이제야 안도감이 들어.   

                                    시스템응답1  \
0                아내분이 출산을 하시는군요. 정말 축하드려요.   
1                       약 종류가 많아 번거로우시겠어요.   
2  고등학교 수업이 중학교 때와는 다르게 갑자기 어려워서 당황스러우시군요.   
3                  재취업 후 첫 월급이라 정말 기쁘시겠어요.   
4           기분 좋으시겠어요. 앞으로는 어떻게 하실 생각이신가요?   

                                               사람문장2  \
0                                      아 지금 정말 신이 나.   
1                        건강할 때 관리 좀 잘할걸 하는 생각이 들더라고.   
2                  아직 학기 초인데 내가 수업에 잘 따라갈 수 있을지 걱정돼.   
3  퇴직 후 다시는 돈을 못 벌 줄 알았는데 이렇게 월급으로 가족에게 맛있는 밥을 살 ...   
4                  빚도 다 갚았으니 당분간은 아무 생각도 안 하며 살고 싶어.   

                                 시스템응답2                               사람문장3  \
0                             잘 된 일이네요.  아기가 점점 클게 벌써 기대가 되네. 내가 많이 놀아줘야지.    
1         현재 상황에서 변화를 주기 위해 어떻게 하면 될까요?          약을 잘 챙겨 먹고 나을 수 있도록 노력해야지.   
2           이 상황에서 할 수 있는 게 어떤 것이 있을까요?       중학교 수업을 들을 때보다 훨씬 더 열심히 할 거야.   
3               이 기분을 유지하려면 어떻게 해야 할까요?           회사생활을 열심히 해서 계속 월급을 받을거야!   
4  빚도 다 갚았으니 당분간은 아무 생각도 안 하며 살고 싶으시군요.                                 NaN   

                         시스템응답3                                      사람문장4  \
0  좋은 아빠가 되실 거 같아요. 진심으로 축하드려요.                                        NaN   
1       약을 잘 챙겨 먹어 건강해지시길 바랄게요.                                        NaN   
2    수업을 어떤 방식으로 열심히 듣는게 좋을까요?   선생님이 강조하신 부분을 필기하고 집에서 매일 수업 내용을 복습하려고 해.   
3   계속 원하시는 대로 회사생활이 이어지길 바랄게요.                                        NaN   
4                           NaN                                        NaN   

                     시스템응답4  
0                       NaN  
1                       NaN  
2  열심히 해서 좋은 결과가 있었으면 좋겠어요.  
3                       NaN  
4                       NaN

In [5]:
df.shape

(69218, 15)

In [6]:
data1 = df[['성별', '사람문장1']]
data2 = df[['성별', '사람문장2']]
data3 = df[['성별', '사람문장3']]
data4 = df[['성별', '사람문장4']]

In [7]:
data1['사람문장'] = data1['사람문장1']
data2['사람문장'] = data2['사람문장2']
data3['사람문장'] = data3['사람문장3']
data4['사람문장'] = data4['사람문장4']

c:\project\venv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\project\venv\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\project\venv\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https:/

In [8]:
data1.drop('사람문장1', axis = 1, inplace = True)

c:\project\venv\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [9]:
data2.drop('사람문장2', axis = 1, inplace = True)
data3.drop('사람문장3', axis = 1, inplace = True)
data4.drop('사람문장4', axis = 1, inplace = True)

In [10]:
total = pd.concat([data1, data2, data3, data4])

In [11]:
total

성별                                           사람문장
0       남성                      아내가 드디어 출산하게 되어서 정말 신이 나.
1       남성        당뇨랑 합병증 때문에 먹어야 할 약이 열 가지가 넘어가니까 스트레스야.
2       여성        고등학교에 올라오니 중학교 때보다 수업이 갑자기 어려워져서 당황스러워.
3       남성  재취업이 돼서 받게 된 첫 월급으로 온 가족이 외식을 할 예정이야. 너무 행복해.
4       여성                   빚을 드디어 다 갚게 되어서 이제야 안도감이 들어.
...    ...                                            ...
69213  NaN                                            NaN
69214  NaN                                            NaN
69215  NaN                                            NaN
69216  NaN                                            NaN
69217  NaN                                            NaN

[276872 rows x 2 columns]

In [12]:
total = total.dropna()

In [13]:
import rhinoMorph
rn = rhinoMorph.startRhino()

def morph_data(line):
    
    morphed_data = rhinoMorph.onlyMorph_list(rn, line, pos=['NNG','NNP','VV','VA','XR','IC','MM','MAG','MAJ'])
    joined_data = ' '.join(morphed_data) # 문자열을 하나로 연결
    if joined_data: # 내용이 있는 경우만 저장하게 함
        line = joined_data
    
    return line

filepath:  c:\project\venv\lib\site-packages
classpath:  c:\project\venv\lib\site-packages\rhinoMorph/lib/rhino.jar
RHINO started!


In [14]:
total['사람문장'] = total['사람문장'].apply(morph_data)

c:\project\venv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
total.head()

성별                               사람문장
0  남성                 아내 드디어 출산 되 정말 신 나
1  남성              당뇨 합병증 약이 가지 넘어가 스트레스
2  여성        고등학교 올라오 중학교 때 수업 갑자기 어렵 당황
3  남성  재취업 되 받 되 첫 월급 오 가족 외식 하 예정 너무 행복
4  여성              빚 드디어 다 갚 되 이제야 안도감 들

In [15]:
X = total.iloc[:,1]
y = total.iloc[:,0]

In [16]:
from sklearn.preprocessing import LabelEncoder

e = LabelEncoder()
e.fit(y)
y = e.transform(y)

In [17]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25, shuffle = True, stratify=y, random_state=1111)

In [18]:
X.shape

(114289,)

In [19]:
y.shape

(114289,)

In [20]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
import numpy as np
import math

In [126]:
max_words = 3000
maxlen = 40

In [127]:
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(train_X)
word_index = tokenizer.word_index

In [128]:
print('전체에서 %s개의 고유한 토큰을 찾았습니다.' % len(word_index))
print('word_index type: ', type(word_index))
# print('word_index: ', word_index)

전체에서 12736개의 고유한 토큰을 찾았습니다.
word_index type:  <class 'dict'>


In [129]:
data = tokenizer.texts_to_sequences(train_X)

print('data 0:', data[0])
print('texts 0:', train_X[0])

data 0: [63, 20, 102, 83, 9, 4, 979, 1081]
texts 0: 0             아 지금 정말 신 나
0    아기 점점 크 벌써 기대 되 많이 놀
Name: 사람문장, dtype: object


In [130]:
data = pad_sequences(data, maxlen=maxlen)

print('data:', data)
print('data 0:', data[0])
print('data 0의 길이:', len(data[0]))

data: [[   0    0    0 ...    4  979 1081]
 [   0    0    0 ...   15  643   22]
 [   0    0    0 ...   42   62  175]
 ...
 [   0    0    0 ...  482  943    1]
 [   0    0    0 ... 1462 2971 1833]
 [   0    0    0 ...  326    1  102]]
data 0: [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0   63   20  102   83    9    4  979 1081]
data 0의 길이: 40


In [131]:
def to_one_hot(sequences, dimension):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

In [132]:
data = to_one_hot(data, dimension=max_words)
labels = np.asarray(train_y).astype('float32')

In [133]:
print('data:', data)
print(len(data[0]))
print('data[0][0:100]:', data[0][0:100])

data: [[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]]
3000
data[0][0:100]: [1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [134]:
validation_ratio = 0.3
validation_len = math.floor(len(train_X) * validation_ratio)

x_train = data[validation_len:]
y_train = labels[validation_len:]
x_val = data[:validation_len]
y_val = labels[:validation_len]

In [135]:
test_data = tokenizer.texts_to_sequences(test_X)
test_data = pad_sequences(test_data, maxlen=maxlen)

In [141]:
test_data = to_one_hot(test_data, dimension=max_words)
test_labels = np.asarray(test_y).astype('float32')

IndexError: arrays used as indices must be of integer (or boolean) type

In [142]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(128, activation='relu', input_shape=(max_words,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [143]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train, epochs=5, batch_size=3, validation_data=(x_val,y_val))
history_dict = history.history

Epoch 1/5
20001/20001 [==============================] - 75s 4ms/step - loss: 0.6576 - acc: 0.5918 - val_loss: 0.6705 - val_acc: 0.5957
Epoch 2/5
20001/20001 [==============================] - 77s 4ms/step - loss: 0.6620 - acc: 0.6154 - val_loss: 0.6813 - val_acc: 0.6050
Epoch 3/5
20001/20001 [==============================] - 77s 4ms/step - loss: 0.6611 - acc: 0.6225 - val_loss: 0.7136 - val_acc: 0.6076
Epoch 4/5
20001/20001 [==============================] - 85s 4ms/step - loss: 0.6634 - acc: 0.6293 - val_loss: 0.6984 - val_acc: 0.6062
Epoch 5/5
20001/20001 [==============================] - 79s 4ms/step - loss: 0.6610 - acc: 0.6338 - val_loss: 0.6991 - val_acc: 0.6107


In [139]:
test_eval = model.evaluate(test_data, test_labels)

893/893 [==============================] - 2s 2ms/step - loss: 0.6865 - acc: 0.6143


In [140]:
print('prediction model loss & acc:', test_eval)

prediction model loss & acc: [0.6864948272705078, 0.614321231842041]
