In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir('C:/pytest')

In [3]:
df1 = pd.read_csv('class0(대출_합법).csv', encoding='cp949')
df2 = pd.read_csv('class1(대출_불법).csv', encoding='cp949')

In [6]:
df1

Content   Label
0     그라나다 할부 조건 시간 전국 어디 중고차 할부 가능 여부 서비스 상담 신청 양식 ...  class0
1     광고 광고 올해 통신 인터넷 보이스 피싱 메모리 해킹 사기 피해 건수 피해액 최민희...  class0
2     춘천 연합뉴스 이해 기자 강원도 교육청 올해 보급 예정 교과서 전자 보이스 피싱 사...  class0
3                                            조선족 보이스 피싱  class0
4                                            조선족 보이스 피싱  class0
...                                                 ...     ...
2980                                 시당 신종 보이스 피싱 통장 어간  class0
2981                                 은행 계좌 번호 보이스 피싱 피해  class0
2982              오후 서민 소송 도우미 변호사 최고 비용 법률 문제 고통 권리 행사  class0
2983                                 실제 보이스 피싱 사건 고객 대박  class0
2984      이해 충남 교육감 대포 충남 교육청 장학사 장사 사건 장학사 문제 무엇 만화 정리  class0

[2985 rows x 2 columns]

In [7]:
df2

Content   Label
0                        저지 레드 다중 과다 채무자 증가 카드 대출 연체 증가  class1
1                        히트 로드 채팅 싸이트 은행 신협 고객 연체 이자 부담  class1
2           보이스 피싱 아우 짜증 이제 그쪽 전화 보이스 피싱 진드기 사람 매트리스 사용  class1
3           보이스 피싱 아우 짜증 이제 그쪽 전화 보이스 피싱 진드기 사람 매트리스 사용  class1
4              보이스 피싱 아우 짜증 이제 그쪽 전화 보이스 피싱 진드기 사람 매트리스  class1
...                                                 ...     ...
1408                                  연체 당일 소액 전마 전국 출장  class1
1409                 휴대폰 소액 결제 문의 입금 통신사 지급 미납 정책 급전 문의  class1
1410  뉴스 기사 직장인 서류 케이블 방송 신용 대출 광고 대출 금액 상환금 직장인 소득 ...  class1
1411           과다 조회 과다 대출 대출 누구 신용 등급 승인 보장 무직자 대출 작업대  class1
1412  휴대폰 소액 결제 서비스 문의 입금 발신 가능 문의 통신사 지급 미납 정책 급전 문...  class1

[1413 rows x 2 columns]

In [8]:
df = pd.concat([df1, df2])

In [10]:
df.isnull().sum()

Content    0
Label      0
dtype: int64

In [11]:
import rhinoMorph
rn = rhinoMorph.startRhino()

def morph_data(line):
    
    morphed_data = rhinoMorph.onlyMorph_list(rn, line, pos=['NNG','NNP','VV','VA','XR','IC','MM','MAG','MAJ'])
    joined_data = ' '.join(morphed_data) # 문자열을 하나로 연결
    if joined_data: # 내용이 있는 경우만 저장하게 함
        line = joined_data
    
    return line

filepath:  c:\project\venv\lib\site-packages
classpath:  c:\project\venv\lib\site-packages\rhinoMorph/lib/rhino.jar
RHINO started!


In [12]:
df['Content'] = df['Content'].apply(morph_data)

In [13]:
df

Content   Label
0     그라나다 할부 조건 시간 전국 중고차 할부 가능 여부 서비스 상담 신청 양식 성명 ...  class0
1     광고 광고 올해 통신 인터넷 보이스 피싱 메모리 해킹 사기 피해 건수 피해액 최민희...  class0
2     춘천 연합뉴스 이해 기자 강원도 교육청 올해 보급 예정 교과서 전자 보이스 피싱 사...  class0
3                                            조선족 보이스 피싱  class0
4                                            조선족 보이스 피싱  class0
...                                                 ...     ...
1408                                  연체 당일 소액 전마 전국 출장  class1
1409                 휴대폰 소액 결제 문의 입금 통신사 지급 미납 정책 급전 문의  class1
1410  뉴스 기사 직장인 서류 케이블 방송 신용 대출 광고 대출 금액 상환금 직장인 소득 ...  class1
1411              과다 조회 과다 대출 대출 신용 등급 승인 보장 무직자 대출 작업대  class1
1412  휴대폰 소액 결제 서비스 문의 입금 발신 가능 문의 통신사 지급 미납 정책 급전 문...  class1

[4398 rows x 2 columns]

In [14]:
X = df.iloc[:,0]
y = df.iloc[:,1]

In [15]:
from sklearn.preprocessing import LabelEncoder

e = LabelEncoder()
e.fit(y)
y = e.transform(y)

In [16]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25, shuffle = True, stratify=y, random_state=1111)

In [66]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
import numpy as np
import math

In [67]:
max_words = 10000
maxlen = 40

In [68]:
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(train_X)
word_index = tokenizer.word_index

In [69]:
print('전체에서 %s개의 고유한 토큰을 찾았습니다.' % len(word_index))
print('word_index type: ', type(word_index))
# print('word_index: ', word_index)

전체에서 3364개의 고유한 토큰을 찾았습니다.
word_index type:  <class 'dict'>


In [70]:
data = tokenizer.texts_to_sequences(train_X)

print('data 0:', data[0])
print('texts 0:', train_X[0])

data 0: [1, 152, 95, 67, 174, 89, 94, 1194, 174, 16, 106, 10, 175, 162]
texts 0: 그라나다 할부 조건 시간 전국 중고차 할부 가능 여부 서비스 상담 신청 양식 성명 핸드폰 번호 상담가 시간 기재


In [71]:
data = pad_sequences(data, maxlen=maxlen)

print('data:', data)
print('data 0:', data[0])
print('data 0의 길이:', len(data[0]))

data: [[   0    0    0 ...   10  175  162]
 [   0    0    0 ...    3   31   15]
 [   0    0    0 ...  936  109   41]
 ...
 [   0    0    0 ...   37    2   21]
 [   0    0    0 ...  776  935 1193]
 [   0    0    0 ...    4    7    6]]
data 0: [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    1  152
   95   67  174   89   94 1194  174   16  106   10  175  162]
data 0의 길이: 40


In [72]:
def to_one_hot(sequences, dimension):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

In [65]:
data = to_one_hot(data, dimension=max_words)
labels = np.asarray(train_y).astype('float32')

In [25]:
print('data:', data)
print(len(data[0]))
print('data[0][0:100]:', data[0][0:100])

data: [[1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
10000
data[0][0:100]: [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.
 0. 0. 0. 0.]


In [26]:
validation_ratio = 0.3
validation_len = math.floor(len(train_X) * validation_ratio)

x_train = data[validation_len:]
y_train = labels[validation_len:]
x_val = data[:validation_len]
y_val = labels[:validation_len]

In [27]:
test_data = tokenizer.texts_to_sequences(test_X)
test_data = pad_sequences(test_data, maxlen=maxlen)

In [28]:
test_data = to_one_hot(test_data, dimension=max_words)
test_labels = np.asarray(test_y).astype('float32')

In [42]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(32, activation='relu', input_shape=(max_words,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [43]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_val,y_val))
history_dict = history.history

Epoch 1/5
73/73 [==============================] - 2s 13ms/step - loss: 0.3271 - acc: 0.9359 - val_loss: 0.1269 - val_acc: 0.9798
Epoch 2/5
73/73 [==============================] - 0s 5ms/step - loss: 0.0807 - acc: 0.9814 - val_loss: 0.0592 - val_acc: 0.9838
Epoch 3/5
73/73 [==============================] - 0s 5ms/step - loss: 0.0386 - acc: 0.9887 - val_loss: 0.0506 - val_acc: 0.9848
Epoch 4/5
73/73 [==============================] - 0s 5ms/step - loss: 0.0232 - acc: 0.9918 - val_loss: 0.0513 - val_acc: 0.9838
Epoch 5/5
73/73 [==============================] - 0s 5ms/step - loss: 0.0152 - acc: 0.9961 - val_loss: 0.0528 - val_acc: 0.9858


In [44]:
model.save('train_model.h5')

In [45]:
from keras.models import load_model
loaded_model = load_model('train_model.h5')
print('model loaded:', loaded_model)

model loaded: <keras.engine.sequential.Sequential object at 0x00000209A15B8348>


In [46]:
test_eval = loaded_model.evaluate(test_data, test_labels)

35/35 [==============================] - 0s 4ms/step - loss: 0.0569 - acc: 0.9818


In [47]:
print('prediction model loss & acc:', test_eval)

prediction model loss & acc: [0.05691513419151306, 0.9818181991577148]
